package lm.Gestion_pedidos.view;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;


/**
 * Clase `ManageIngredient` que representa la ventana en la que se van a modificar y crear nuevos ingredintes que compondran los productos.
 * <p>
 * Esta clase extiende de `JFrame` y se encarga de inicializar los componentes visuales
 * de la ventana principal mediante el método `initComponents()`.
 * Proporciona métodos de acceso (`getters`) a todos los botones de la interfaz, 
 * permitiendo así que el controlador pueda modificar sus propiedades o añadirles eventos.
 * </p>
 * @author Lucas Morandeira Parejo
 */

public class ManageIngredient extends javax.swing.JDialog {


    
    public ManageIngredient() {
        initComponents();
    }
    
    public JButton getBtnSaveIngredient() {
        return manageIngredientSaveIngredient;
    }
    
    public JButton getBtnDeleteIngredient() {
        return manageIngredientDeleteIngredient;
    }
    
    public JTextField getEdtNameIngredient() {
        return manageIngredientName;
    }
    
    public JTextField getEdtPriceIngredient() {
        return manageIngredientPrice;
    }
    
    public JTable getTableIngredient() {
        return manageIngredientTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        manageIngredientName = new javax.swing.JTextField();
        manageIngredientPrice = new javax.swing.JTextField();
        manageIngredientSaveIngredient = new javax.swing.JButton();
        manageIngredientDeleteIngredient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageIngredientTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(26, 44, 68));

        manageIngredientName.setBackground(new java.awt.Color(26, 44, 68));
        manageIngredientName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageIngredientName.setForeground(new java.awt.Color(255, 255, 255));
        manageIngredientName.setBorder(null);

        manageIngredientPrice.setBackground(new java.awt.Color(26, 44, 68));
        manageIngredientPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageIngredientPrice.setForeground(new java.awt.Color(255, 255, 255));
        manageIngredientPrice.setBorder(null);

        manageIngredientSaveIngredient.setBackground(new java.awt.Color(26, 44, 68));
        manageIngredientSaveIngredient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageIngredientSaveIngredient.setForeground(new java.awt.Color(255, 255, 255));
        manageIngredientSaveIngredient.setText("Guardar");
        manageIngredientSaveIngredient.setBorder(null);

        manageIngredientDeleteIngredient.setBackground(new java.awt.Color(26, 44, 68));
        manageIngredientDeleteIngredient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageIngredientDeleteIngredient.setForeground(new java.awt.Color(255, 255, 255));
        manageIngredientDeleteIngredient.setText("Eliminar Ingrediente");
        manageIngredientDeleteIngredient.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrediente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Precio");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(manageIngredientName, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageIngredientPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(manageIngredientSaveIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(manageIngredientDeleteIngredient)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageIngredientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageIngredientPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageIngredientSaveIngredient)
                    .addComponent(manageIngredientDeleteIngredient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addGap(30, 30, 30))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 120));

        manageIngredientTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageIngredientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(manageIngredientTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 120, 670, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton manageIngredientDeleteIngredient;
    private javax.swing.JTextField manageIngredientName;
    private javax.swing.JTextField manageIngredientPrice;
    private javax.swing.JButton manageIngredientSaveIngredient;
    private javax.swing.JTable manageIngredientTable;
    // End of variables declaration//GEN-END:variables
}
