package lm.Gestion_pedidos.view;

import javax.swing.JComboBox;
import javax.swing.JLabel;


/**
 *
 * @author Lucas
 */

public class Statistics extends javax.swing.JDialog {

    /**
     * Creates new form Statistics
     */
 
    public Statistics() {
        initComponents();
    }
    
    public JLabel getTotalOrdersForMonth() {
        return totalOrdersForMonth;
    }
    
    public JLabel getTotalIncomeForMonth() {
        return totalIncomeForMonth;
    }
    
    public JLabel getTotalIncomeForYear() {
        return totalIncomeForYear;
    }
    
    public JLabel getTotalOrdersForYear() {
        return totalOrdersForYear;
    }
    
    
    public JLabel getTotalCustomersForMonth() {
        return customersForMonth;
    }
    
    public JComboBox getBoxMonth() {
        return month;
    }
    
    public JLabel getBestCustomer() {
        return bestCustomer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalOrdersForMonth = new javax.swing.JLabel();
        totalIncomeForMonth = new javax.swing.JLabel();
        customersForMonth = new javax.swing.JLabel();
        totalOrdersForYear = new javax.swing.JLabel();
        month = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        totalIncomeForYear = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bestCustomer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 44, 68));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pedidos en el mes de");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total ingresado en el mes");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Clientes totales en el mes");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total pedidos del año en curso");

        totalOrdersForMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalOrdersForMonth.setForeground(new java.awt.Color(255, 255, 255));
        totalOrdersForMonth.setText("0");

        totalIncomeForMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalIncomeForMonth.setForeground(new java.awt.Color(255, 255, 255));
        totalIncomeForMonth.setText("0");

        customersForMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customersForMonth.setForeground(new java.awt.Color(255, 255, 255));
        customersForMonth.setText("0");

        totalOrdersForYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalOrdersForYear.setForeground(new java.awt.Color(255, 255, 255));
        totalOrdersForYear.setText("0");

        month.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total ingresado en el año en curso");

        totalIncomeForYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalIncomeForYear.setForeground(new java.awt.Color(255, 255, 255));
        totalIncomeForYear.setText("0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cliente del mes:");

        bestCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bestCustomer.setForeground(new java.awt.Color(255, 255, 255));
        bestCustomer.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(61, 61, 61)
                                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalOrdersForYear)
                            .addComponent(customersForMonth)
                            .addComponent(totalIncomeForMonth)
                            .addComponent(totalOrdersForMonth)
                            .addComponent(totalIncomeForYear)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(bestCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalOrdersForMonth)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalIncomeForMonth))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customersForMonth))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bestCustomer))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(totalOrdersForYear))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalIncomeForYear))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bestCustomer;
    private javax.swing.JLabel customersForMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JLabel totalIncomeForMonth;
    private javax.swing.JLabel totalIncomeForYear;
    private javax.swing.JLabel totalOrdersForMonth;
    private javax.swing.JLabel totalOrdersForYear;
    // End of variables declaration//GEN-END:variables
}
